CREATE TABLE IF NOT EXISTS players(
    id INTEGER PRIMARY KEY,
    name TEXT,
    birthday TEXT,
    leadership INTEGER,
    loyalty INTEGER,
    desire_for_win INTEGER,
    greed INTEGER,
    intelligence INTEGER,
    work_ethic INTEGER,
    bats TEXT,
    throws TEXT,
    position TEXT,
    retired INTEGER);

CREATE TABLE IF NOT EXISTS batting_stats(
    player_id INTEGER,
    position TEXT,
    start_year INTEGER,
    end_year INTEGER,
    g INTEGER,
    ab INTEGER,
    h INTEGER,
    double INTEGER,
    triple INTEGER,
    hr INTEGER,
    rbi INTEGER,
    r INTEGER,
    bb INTEGER,
    hp INTEGER,
    sf INTEGER,
    k INTEGER,
    sb INTEGER,
    cs INTEGER,
    vorp REAL,
    war REAL,
    avg REAL,
    obp REAL,
    slg REAL,
    ops REAL,
    babip REAL,
    krate REAL,
    bbrate REAL,
    PRIMARY KEY (player_id),
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS pitching_stats(
    player_id INTEGER,
    start_year INTEGER,
    end_year INTEGER,
    g INTEGER,
    gs INTEGER,
    w INTEGER,
    l INTEGER,
    sv INTEGER,
    outs INTEGER,
    ha INTEGER,
    r INTEGER,
    er INTEGER,
    hr INTEGER,
    bb INTEGER,
    k INTEGER,
    cg INTEGER,
    sho INTEGER,
    vorp REAL,
    war REAL,
    era REAL,
    whip REAL,
    k9 REAL,
    bb9 REAL,
    kbb REAL,
    PRIMARY KEY (player_id),
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS season_batting_stats(
    year INTEGER,
    player_id INTEGER,
    team_id INTEGER,
    position TEXT,
    g INTEGER,
    ab INTEGER,
    h INTEGER,
    double INTEGER,
    triple INTEGER,
    hr INTEGER,
    rbi INTEGER,
    r INTEGER,
    bb INTEGER,
    hp INTEGER,
    sf INTEGER,
    k INTEGER,
    sb INTEGER,
    cs INTEGER,
    vorp REAL,
    war REAL,
    avg REAL,
    obp REAL,
    slg REAL,
    ops REAL,
    babip REAL,
    krate REAL,
    bbrate REAL,
    PRIMARY KEY (player_id, year, team_id),
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS season_pitching_stats(
    year INTEGER,
    player_id INTEGER,
    team_id INTEGER,
    g INTEGER,
    gs INTEGER,
    w INTEGER,
    l INTEGER,
    sv INTEGER,
    outs INTEGER,
    ha INTEGER,
    r INTEGER,
    er INTEGER,
    hr INTEGER,
    bb INTEGER,
    k INTEGER,
    cg INTEGER,
    sho INTEGER,
    vorp REAL,
    war REAL,
    era REAL,
    whip REAL,
    k9 REAL,
    bb9 REAL,
    kbb REAL,
    PRIMARY KEY (player_id, year),
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS hall_of_fame (
    player_id INTEGER,
    year INTEGER,
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS hall_of_fame_eligible (
    player_id INTEGER,
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS waiver_wire (
    date TEXT,
    player_id INTEGER,
    FOREIGN KEY (player_id) REFERENCES players(id));

CREATE TABLE IF NOT EXISTS current_date (
    date TEXT);